# Welcome to Jekyll!
#


title: Saanjh
email: saanjh.proj@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We conduct most of our programs at Sri Singh Sabha Gurdwara, Surrey BC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://saanjh.ca"
github_username:  saanjh-org
permalink: /blog/:year/:month/:day/:title/
# Build settings
theme: minima
plugins:
  - jekyll-feed